# Generated by Django 6.0.4 on 2026-04-28 22:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochurePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('full_bleed_image', 3), ('pull_quote', 5), ('two_column', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('left', 6), ('right', 6)]], {})})),
            ],
            options={
                'verbose_name': 'Brochure page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('full_bleed_image', 3), ('pull_quote', 5), ('two_column', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 2)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('left', 6), ('right', 6)]], {})})),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MembersIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Members index page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
