# Generated by Django 6.0.4 on 2026-04-28 23:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('rich_text', 5), ('full_bleed_image', 7), ('pull_quote', 9), ('two_column', 11)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Large headline displayed over the hero'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Request access'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('event_name', 1), ('cta_label', 2), ('show_cta', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('quote', 8), ('attribution', 6)]], {}), 10: ('wagtail.blocks.RichTextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('left', 10), ('right', 10)]], {})}),
        ),
    ]
